apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169897051
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169897051
    app.kubernetes.io/part-of: test-app-169897051
  name: go-169897051sdn1
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-169897051
    weight: null
status: {}
